name: olisturm
favicon: null
layout_spectrum: 0.45366
typography_spectrum: 0.31204
title: Oliver Sturm
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fd7323'
    - '#33396c'
    - '#000000'
    - '#666a90'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
