name: olisturm
favicon: null
layout_spectrum: 0.2909567952156067
typography_spectrum: 0.07362
title: Oliver Sturm
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5283590317703784
  lightness: 0.773898093495518
  saturation: 0.5354675448033959
  rhythmicContrast: 0.7024120150599629
purpose: []
